name: smart_forms
description: A flutter forms generator based on objects with multiple parameters.
version: 1.0.2
homepage: https://github.com/fjbatresv/flutter_smart_forms

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
