name: smart_forms
description: A flutter forms generator based on objects with multiple parameters.
version: 2.0.1
homepage: https://github.com/fjbatresv/flutter_smart_forms

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
